site_name: Bioinformatics Tutorials
theme:
    name: 'material'
    palette:
        primary: 'pink'
        accent: 'pink'
repo_name: 'HadrienG/tutorials'
repo_url: 'https://github.com/HadrienG/tutorials'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/HadrienG'
        - type: 'twitter'
          link: 'https://twitter.com/HGourle'

# extensions
markdown_extensions:
    - admonition
    - codehilite
    - markdown.extensions.toc:
        permalink: true

# page tree
pages:
    - Home: index.md
    - The command-line: command_line.md
    - File Formats: file_formats.md
    - Quality Control and Trimming: qc.md
    - Mapping and Variant Calling: mapping.md
    - De-novo Genome Assembly: assembly.md
    - Genome Annotation: annotation.md
    - Pan-Genome Analysis: pan_genome.md
    - Metabarcoding: 16S.md
    - Whole Metagenome Sequencing: wms.md
    - Metagenome assembly: meta_assembly.md
    - RNA-Seq: rna.md
    - Introduction to Nanopore Sequencing: nanopore.md
